version: "3.9"

services:
  # 🧠 MongoDB
  mongo:
    image: mongo:8.0
    container_name: rag_backend-mongo-1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rag_net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  # 🚀 FastAPI RAG Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_backend-api
    restart: always
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - rag_net


networks:
  rag_net:
    driver: bridge

volumes:
  mongo_data:
