services:
  # 🧠 MongoDB (for your RAG backend)
  mongo:
    image: mongo:8.0
    container_name: rag_backend-mongo-1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - rag_net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  rag_net:
    driver: bridge

volumes:
  mongo_data:

